DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS entry;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  admin INTEGER NOT NULL,
  fullname TEXT NOT NULL
);

CREATE TABLE entry (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  score INTEGER,
  user_id INTEGER,
  entry_date TEXT,
  FOREIGN KEY (user_id) REFERENCES user (id)
);
